services:
  avalanche:
    container_name: avalanche
    image: quay.io/freshtracks.io/avalanche
    ports:
      - 9101:9101
    command:
      -  "--metric-count=1"
      -  "--series-count=500"
      -  "--label-count=20"
      -  "--series-interval=20000000"
      -  "--metric-interval=100009999"
      -  "--port=9101"
    networks:
      - vm_net
    restart: always
  vmagent-monitoring:
    container_name: vmagent-monitoring
    image: victoriametrics/vmagent:v1.103.0
    depends_on:
      - "victoriametrics"
    ports:
      - 8429
    volumes:
      - vmagent-monitoring:/vmagentdata
      - ./monitoring.yml:/etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    networks:
      - vm_net
    restart: always
  vmagent-with-aggregation:
    container_name: vmagent-with-aggregation
    image: victoriametrics/vmagent:v1.103.0
    depends_on:
      - "victoriametrics"
    ports:
      - 8429:8429
    volumes:
      - vmagentdata-with-aggregation:/vmagentdata
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./stream_aggr_config.yml:/etc/prometheus/stream_aggr_config.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--streamAggr.config=/etc/prometheus/stream_aggr_config.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
      - "--promscrape.config.strictParse=false"
    networks:
      - vm_net
    restart: always

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.54.1
    depends_on:
      - "victoriametrics"
    ports:
      - 9090:9090
    volumes:
      - prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - vm_net
    restart: always

  # VictoriaMetrics instance, a single process responsible for
  # storing metrics and serve read requests.
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.103.0
    ports:
      - 8428:8428
    volumes:
      - vmdata:/storage
    command:
      - "--storageDataPath=/storage"
      - "--vmalert.proxyURL=http://vmalert:8880"
    networks:
      - vm_net
    restart: always

  # Grafana instance configured with VictoriaMetrics as datasource
  grafana:
    container_name: grafana
    image: grafana/grafana:10.4.2
    depends_on:
      - "victoriametrics"
    ports:
      - 3000:3000
    volumes:
      - grafanadata:/var/lib/grafana
      - ./provisioning/datasources/prometheus-datasource:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./../../dashboards/victoriametrics.json:/var/lib/grafana/dashboards/vm.json
      - ./../../dashboards/vmagent.json:/var/lib/grafana/dashboards/vmagent.json
      - ./../../dashboards/vmalert.json:/var/lib/grafana/dashboards/vmalert.json
    networks:
      - vm_net
    restart: always

volumes:
  prometheus: {}
  vmagent-monitoring: {}
  vmagentdata-with-aggregation: {}
  vmdata: {}
  grafanadata: {}
networks:
  vm_net:
