global:
  scrape_interval: 5s

scrape_configs:
- job_name: 'vmagent-monitoring'
  static_configs:
    - targets: ['vmagent-monitoring:8429']
- job_name: 'prometheus'
  static_configs:
    - targets: ['prometheus:9090']
- job_name: 'vmagent-with-aggregation'
  static_configs:
    - targets: ['vmagent-with-aggregation:8429']
- job_name: 'victoriametrics'
  static_configs:
    - targets: ['victoriametrics:8428']