version: '3'

services:
  vlogs:
    image: golang:1.21.5-alpine
    restart: always
    working_dir: /go/src/app/vm
    volumes:
      - ./../..:/go/src/app/vm
      - /mnt/vlogs:/vlogs
    command:
      - go
      - run
      - app/victoria-logs/main.go
      - -storageDataPath=/vlogs
    ports:
      - '9429:9428'

  generator:
    image: golang:1.21.5-alpine
    restart: always
    working_dir: /go/src/app
    volumes:
      - ./generator:/go/src/app
      - ./source_logs:/go/src/source_logs
    command:
      - go
      - run
      - main.go
      - -logsPath=/go/src/source_logs/logs
      - -outputRateLimitItems=10000
      - -outputRateLimitPeriod=1s
      - -syslog.addr=fluentbit:5140
      - -syslog.addr2=fluentbit:5140
      - -logs.randomSuffix=false
    depends_on: [ fluentbit ]

  fluentbit:
    image: cr.fluentbit.io/fluent/fluent-bit:2.1.4
    volumes:
      - ./single/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on: [vlogs]
    ports:
      - "5140:5140"

volumes:
  loki:
