name: license-check
on:
  push:
    paths:
      - 'vendor'
  pull_request:
    paths:
      - 'vendor'
permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@main
        with:
          go-version: stable
          cache: false
        id: go
      - name: Code checkout
        uses: actions/checkout@master
      - name: Cache Go artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin
          key: go-artifacts-${{ runner.os }}-check-licenses-${{ hashFiles('go.sum', 'Makefile', 'app/**/Makefile') }}
          restore-keys: go-artifacts-${{ runner.os }}-check-licenses-
      - name: Check License
        run: make check-licenses
